controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation
app_prestataire_form:
    path: '/prestataire/form/{id}'
    controller: App\Controller\PrestataireController::prestataireForm
download_promotion_pdf:
    path: '/promotion/download/{idpromo}/{id}'
    controller: App\Controller\PrestataireController::downloadPdf


